name: flutter_login
description: "A new Flutter project."

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Ensures compatibility

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5

  # Local Database & Storage
  sqflite: ^2.3.3+2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # Network & APIs
  http: ^1.2.2
  connectivity_plus: ^6.1.0

  # Utility & State Management
  provider: ^6.1.2
  uuid: ^3.0.6
  window_manager: ^0.4.3
  flutter_screenutil: ^5.9.3

  # PDF Handling
  flutter_pdfview: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # Assets (Images & Fonts)
  assets:
    - assets/Seed.png
    - assets/bocwr.png
    - assets/dgfasli.png
    - assets/electrical.png
    - assets/environment.png
    - assets/esi_pf.png
    - assets/fire.png
    - assets/food.png
    - assets/legal2024.png
    - assets/2025.png
    - assets/lift.png
    - assets/others.png
    - assets/peso.png
    - assets/factory_act.png
    - assets/fonts/aAtomicMd.ttf  # Corrected indentation
    - assets/fonts/Typo.otf

  # Custom Fonts
  fonts:
    - family: aAtomicMd
      fonts:
        - asset: assets/fonts/aAtomicMd.ttf

    - family: Typo
      fonts:
        - asset: assets/fonts/Typo.otf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/legal_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/legal_icon.png"
platforms:
  android:
  ios:
  windows:
  linux:
  macos:
